### ISSUE TITLE
Create Dashboard Page and Remaining Tables

### ISSUE THREAD

**Issue by hwang26** [hwang26/basic-budget-app#18]
## Acceptance Criteria:

- Complete the dependent tickets
- The Dashboard will be a functional mockup

## Dependent Tickets

- [x] #29 User Info Mockup
- [x] #30 Nav Bar Mockup
- [x] #31 Uninspected Transactions Component
- [ ] #32 Budget Component

**Comment by hwang26** [comment]
## Dependent Tickets

**Comment by hwang26** [comment]
This ticket is unnecessary as a tracking ticket. For tracking specific features, we can just create new milestones.
